config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :categories
      resources :user_badges
      resources :prompts
      resources :segments
      resources :languages
      resources :levels
      resources :segment_corrections
      resources :corrections
      resources :badges
      resources :posts
      resources :user_languages

      root to: "users#index"
    end
  devise_for :users

  resources :posts do
    resources :corrections
  end

  resources :prompts
  resources :users
  resources :resources, only: :index

  root to: 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/correction.rb
class Correction < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many   :segment_corrections
  has_many   :segments, through: :segment_corrections

  accepts_nested_attributes_for :segment_corrections,
                                reject_if: proc { |attributes| attributes['entry'].blank? }
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/language.rb
class Language < ApplicationRecord
end

app/models/level.rb
class Level < ApplicationRecord
end

app/models/note.rb
class Note < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :language
  belongs_to :level
  belongs_to :prompt, required: false
  belongs_to :category

  has_many :segments
  has_many :corrections
  has_many :segment_corrections, through: :segments

  accepts_nested_attributes_for :corrections

  acts_as_taggable_on :tags

  def self.list(filter)
    by_user(filter[:user_id]).
    limit(filter[:limit] || 10)
  end

  def self.by_user(user_id)
    return self if user_id.nil?
    where(user_id: user_id)
  end
end

app/models/prompt.rb
class Prompt < ApplicationRecord
  belongs_to :user
  belongs_to :language
  belongs_to :level

  def self.list(_filters)
    all
  end
end

app/models/segment.rb
class Segment < ApplicationRecord
  belongs_to :post
  has_many   :segment_corrections
end

app/models/segment_correction.rb
class SegmentCorrection < ApplicationRecord
  belongs_to :segment
  belongs_to :correction
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  has_many :posts
  has_many :prompts
  has_many :corrections
  has_many :user_native_languages
  has_many :user_learning_languages

  has_many :learning_languages, through: :user_learning_languages, source: :language
  has_many :native_languages,   through: :user_native_languages,   source: :language

  has_many :languages_learning, through: :learning_languages, source: :language
  has_many :languages_native,   through: :native_languages,   source: :language
end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
end

app/models/user_language.rb
class UserLanguage < ApplicationRecord
  belongs_to :language
  belongs_to :user
  belongs_to :level
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :get_user, only: [:show, :edit]

  def show
    @latest_posts = Post::Operation::Index.(
      params: {
        limit: 5,
        user_id: current_user.id
      }
    )[:presented]

    render cell(User::Cell::Show, @user, latest_posts: @latest_posts)
  end

  def edit
    render cell(User::Cell::Edit,
      current_user,
      languages: Language.all,
      levels: Level.all
    )
  end

  def update
    res = User::Operation::Update.(params: user_params.merge(id: current_user.id))
    redirect_to user_path res[:presented].model
  end

  private

  def get_user
    @user = User::Operation::Show.(
      params: {
        id: params[:id] || current_user.id
      }
    )[:presented]
  end

  def user_params
    params.require(:user).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/corrections_helper.rb
module CorrectionsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/prompts_helper.rb
module PromptsHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="card mt-3">
  <div class="card-body">
    <%= form_with model: @user do |f| %>
      <div class="form-row mb-2">
        <div class="col">
          <%= f.text_area :about, placeholder: 'Write something about yourself', class: 'form-control' %>
        </div>
      </div>
      <div class="form-row">
          <h4>Native Languages</h4>
          <%= f.fields_for :native_languages do |u| %>
            <div class="col-md-12 mb-2">
              <%= u.select :language_id, Language.all.map{|l| [l.name, l.id]}, { prompt: 'Select Language'}, class: 'form-control' %>
              <%= u.hidden_field :level_id %>
            </div>
          <% end %>
      </div>
      <div class="form-row mt-3">
        <h4>Learning Languages</h4>
        <%= f.fields_for :learning_languages do |u| %>
         <div class="col-md-12 mb-2">
           <%= u.select :language_id, Language.all.map{|l| [l.name, l.id]}, { prompt: 'Select Language' }, class: "form-control" %>
            <%= u.select :level_id, Level.all.map{|l| [l.name, l.id]}, { prompt: 'Select Level' }, class: "form-control" %>
          </div>
        <% end %>
      </div>
      <div class="form-row mt-3">
        <div class="col">
          <%= f.button "Update", class: 'btn btn-primary' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="card mb-3 mt-3">
  <div class="card-header">
    <%= render "users/user_title", user: @user %>
  </div>
  <div class="card-body">
    <div class="row">
      <div class="col-sm">
        <%= @user.about ||= "No about section yet :(" %>
      </div>
    </div>
  </div>
  <div class="card-footer">
    <%= link_to 'Edit Profile', edit_user_url(@user)%>
  </div>
</div>

<h1>Latest Posts</h1>

<%= render @latest_posts %>