config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :categories
      resources :user_badges
      resources :prompts
      resources :segments
      resources :languages
      resources :levels
      resources :segment_corrections
      resources :corrections
      resources :badges
      resources :posts
      resources :user_languages

      root to: "users#index"
    end
  devise_for :users

  resources :posts do
    resources :corrections
  end

  resources :prompts
  resources :users
  resources :resources, only: :index

  root to: 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/correction.rb
class Correction < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many   :segment_corrections
  has_many   :segments, through: :segment_corrections

  accepts_nested_attributes_for :segment_corrections,
                                reject_if: proc { |attributes| attributes['entry'].blank? }
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/language.rb
class Language < ApplicationRecord
end

app/models/level.rb
class Level < ApplicationRecord
end

app/models/note.rb
class Note < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :language
  belongs_to :level
  belongs_to :prompt, required: false
  belongs_to :category

  has_many :segments
  has_many :corrections
  has_many :segment_corrections, through: :segments

  accepts_nested_attributes_for :corrections

  acts_as_taggable_on :tags

  def self.list(filter)
    by_user(filter[:user_id]).
    limit(filter[:limit] || 10)
  end

  def self.by_user(user_id)
    return self if user_id.nil?
    where(user_id: user_id)
  end
end

app/models/prompt.rb
class Prompt < ApplicationRecord
  belongs_to :user
  belongs_to :language
  belongs_to :level

  def self.list(_filters)
    all
  end
end

app/models/segment.rb
class Segment < ApplicationRecord
  belongs_to :post
  has_many   :segment_corrections
end

app/models/segment_correction.rb
class SegmentCorrection < ApplicationRecord
  belongs_to :segment
  belongs_to :correction
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  has_many :posts
  has_many :prompts
  has_many :corrections
  has_many :user_native_languages
  has_many :user_learning_languages

  has_many :learning_languages, through: :user_learning_languages, source: :language
  has_many :native_languages,   through: :user_native_languages,   source: :language

  has_many :languages_learning, through: :learning_languages, source: :language
  has_many :languages_native,   through: :native_languages,   source: :language
end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
end

app/models/user_language.rb
class UserLanguage < ApplicationRecord
  belongs_to :language
  belongs_to :user
  belongs_to :level
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/prompts_helper.rb
module PromptsHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/admin/application.html.erb
<%#
# Application Layout

This view template is used as the layout
for every page that Administrate generates.

By default, it renders:
- Navigation
- Content for a search bar
  (if provided by a `content_for` block in a nested page)
- Flashes
- Links to stylesheets and JavaScripts
%>

<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <meta charset="utf-8">
    <meta name="robots" content="noodp, noydir, index, follow">
    <meta name="viewport" content="initial-scale=1">
    <title>
      <%= content_for(:title) || 'Dashboard' %> - <%= Rails.application.class.module_parent_name.titlecase %>
    </title>

    <%= csp_meta_tag %>
    <%= javascript_pack_tag 'administrate', 'data-turbolinks-track': 'reload' %>

    <%= render "stylesheet" %>
    <%= csrf_meta_tags %>

    <meta name="turbolinks-root" content="/admin">
  </head>
  <body>
    <div class="app-container">
      <%= render "navigation" -%>

      <main class="main-content" role="main">
        <%= render "flashes" -%>
        <%= yield %>
      </main>
    </div>

    <div style="display: none; width: 0; height: 0; overflow: hidden; position: absolute">
      <%= render "icons" %>
    </div>
    <%= render "javascript" %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tagengo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'stylesheets' %>
    <link rel="stylesheet"
              href="https://fonts.googleapis.com/css?family=Noto+Sans+TC">
  </head>

  <body>
    <div class="container-fluid">
      <div class="row min-vh-100">
        <div class="col-sm-9 bg-dark-grey">
          <nav class="navbar navbar-expand-lg sticky-top navbar-dark">
              <a class="navbar-brand" href="#">Tagengo</a>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                  <li class="nav-item"><%= link_to 'Profile', current_user, class: "nav-link" %></li>
                  <li class="nav-item"><%= link_to 'Posts', posts_url, class: "nav-link active" %></li>
                  <li class="nav-item"><%= link_to 'New Post', new_post_url, class: "nav-link" %></li>
                  <li class="nav-item"><%= link_to 'Prompts', prompts_url, class: "nav-link" %></li>
                  <li class="nav-item"><%= link_to 'Resources', resources_url, class: "nav-link" %></li>
                </ul>
              </div>
          </nav>
          <div class="container-fluid" id="content">
            <%= yield %>
          </div>
        </div>
        <div class="col-sm-3 bg-light-grey">
          <div class="d-flex flex-column h-100">
            <div class="card-header">
              <%= cell(User::Cell::Title, current_user) if signed_in? %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/resources/index.html.erb
<% page = MetaInspector.new('https://wanikani.com') %>

<h1>Resources</h1>

<div class="row">
  <div class="col">
    <div class="card">
      <img class="card-img-top" src="<%= page.images.best %>">
      <div class="card-body">
        <h5 class="card-title"><%= page.best_title %></h5>
        <p class="card-text"><%= page.best_description %></p>
        <a href="#" class="btn btn-primary">Visit Website</a>
      </div>
    </div>
  </div>

  <% page = MetaInspector.new('https://www.tofugu.com/japanese/learn-hiragana/') %>

  <div class="col">
    <div class="card">
      <img class="card-img-top" src="<%= page.images.best %>">
      <div class="card-body">
        <h5 class="card-title"><%= page.best_title %></h5>
        <p class="card-text"><%= page.best_description %></p>
        <a href="#" class="btn btn-primary">Visit Website</a>
      </div>
    </div>
  </div>

  <% page = MetaInspector.new('https://www3.nhk.or.jp/news/easy/') %>

  <div class="col">
    <div class="card">
      <img class="card-img-top" src="<%= page.images.best %>">
      <div class="card-body">
        <h5 class="card-title"><%= page.best_title %></h5>
        <p class="card-text"><%= page.best_description %></p>
        <a href="#" class="btn btn-primary">Visit Website</a>
      </div>
    </div>
  </div>
</div>